/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAdvisorRouteImport } from './routes/ai-advisor'
import { Route as BusinessAnalysisRouteImport } from './routes/business-analysis'
import { Route as ComparisonsRouteImport } from './routes/comparisons'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LocationAnalysisRouteImport } from './routes/location-analysis'
import { Route as MarketOpportunitiesRouteImport } from './routes/market-opportunities'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SavedAnalysesRouteImport } from './routes/saved-analyses'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAnalysisRoute = BusinessAnalysisRouteImport.update({
  id: '/business-analysis',
  path: '/business-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonsRoute = ComparisonsRouteImport.update({
  id: '/comparisons',
  path: '/comparisons',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationAnalysisRoute = LocationAnalysisRouteImport.update({
  id: '/location-analysis',
  path: '/location-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketOpportunitiesRoute = MarketOpportunitiesRouteImport.update({
  id: '/market-opportunities',
  path: '/market-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedAnalysesRoute = SavedAnalysesRouteImport.update({
  id: '/saved-analyses',
  path: '/saved-analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/business-analysis': typeof BusinessAnalysisRoute
  '/comparisons': typeof ComparisonsRoute
  '/dashboard': typeof DashboardRoute
  '/location-analysis': typeof LocationAnalysisRoute
  '/market-opportunities': typeof MarketOpportunitiesRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/saved-analyses': typeof SavedAnalysesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/business-analysis': typeof BusinessAnalysisRoute
  '/comparisons': typeof ComparisonsRoute
  '/dashboard': typeof DashboardRoute
  '/location-analysis': typeof LocationAnalysisRoute
  '/market-opportunities': typeof MarketOpportunitiesRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/saved-analyses': typeof SavedAnalysesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/business-analysis': typeof BusinessAnalysisRoute
  '/comparisons': typeof ComparisonsRoute
  '/dashboard': typeof DashboardRoute
  '/location-analysis': typeof LocationAnalysisRoute
  '/market-opportunities': typeof MarketOpportunitiesRoute
  '/recommendations': typeof RecommendationsRoute
  '/reports': typeof ReportsRoute
  '/saved-analyses': typeof SavedAnalysesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-advisor'
    | '/business-analysis'
    | '/comparisons'
    | '/dashboard'
    | '/location-analysis'
    | '/market-opportunities'
    | '/recommendations'
    | '/reports'
    | '/saved-analyses'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-advisor'
    | '/business-analysis'
    | '/comparisons'
    | '/dashboard'
    | '/location-analysis'
    | '/market-opportunities'
    | '/recommendations'
    | '/reports'
    | '/saved-analyses'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/ai-advisor'
    | '/business-analysis'
    | '/comparisons'
    | '/dashboard'
    | '/location-analysis'
    | '/market-opportunities'
    | '/recommendations'
    | '/reports'
    | '/saved-analyses'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAdvisorRoute: typeof AiAdvisorRoute
  BusinessAnalysisRoute: typeof BusinessAnalysisRoute
  ComparisonsRoute: typeof ComparisonsRoute
  DashboardRoute: typeof DashboardRoute
  LocationAnalysisRoute: typeof LocationAnalysisRoute
  MarketOpportunitiesRoute: typeof MarketOpportunitiesRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ReportsRoute: typeof ReportsRoute
  SavedAnalysesRoute: typeof SavedAnalysesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor': {
      id: '/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-analysis': {
      id: '/business-analysis'
      path: '/business-analysis'
      fullPath: '/business-analysis'
      preLoaderRoute: typeof BusinessAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparisons': {
      id: '/comparisons'
      path: '/comparisons'
      fullPath: '/comparisons'
      preLoaderRoute: typeof ComparisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-analysis': {
      id: '/location-analysis'
      path: '/location-analysis'
      fullPath: '/location-analysis'
      preLoaderRoute: typeof LocationAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-opportunities': {
      id: '/market-opportunities'
      path: '/market-opportunities'
      fullPath: '/market-opportunities'
      preLoaderRoute: typeof MarketOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-analyses': {
      id: '/saved-analyses'
      path: '/saved-analyses'
      fullPath: '/saved-analyses'
      preLoaderRoute: typeof SavedAnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAdvisorRoute: AiAdvisorRoute,
  BusinessAnalysisRoute: BusinessAnalysisRoute,
  ComparisonsRoute: ComparisonsRoute,
  DashboardRoute: DashboardRoute,
  LocationAnalysisRoute: LocationAnalysisRoute,
  MarketOpportunitiesRoute: MarketOpportunitiesRoute,
  RecommendationsRoute: RecommendationsRoute,
  ReportsRoute: ReportsRoute,
  SavedAnalysesRoute: SavedAnalysesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
